name: Azure PowerShell Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure PowerShell
      uses: azure/setup-powershell@v2
      with:
        pwsh-version: '7.2.1' # Specify the version of PowerShell you want to use.

    - name: Login to Azure
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        $ErrorActionPreference = "Stop"
        $creds = ConvertFrom-Json $env:AZURE_CREDENTIALS
        Connect-AzAccount -Credential $creds

    - name: Execute PowerShell Script
      run: |
        pwsh -File ./C:\Users\anilk\OneDrive\Documents\Optum\PS for PAT token.ps1 # Update with your script's path
              - name: Logout from Azure
      run: |
        Disconnect-AzAccount
