# Authenticate with Azure using the service principal
az login --service-principal -u <SP_CLIENT_ID> -p <SP_CLIENT_SECRET> --tenant <TENANT_ID>

# Get the access token for Databricks
ACCESS_TOKEN=$(az account get-access-token --resource https://databricks.azure.net --query accessToken -o tsv)

# Print the access token (optional)
echo "Access Token: $ACCESS_TOKEN"
